# Generated by Django 2.2.9 on 2020-06-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200603_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
